### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Justinezgh** [Justinezgh/ssnpe_desc_project#2]
- [ ] NPE from prior 
     - [ ] without score 
     - [ ] with score 
- [ ]  SNPE and reweighting afterwards 
- [ ] NLE from proposal 
     - [ ] add the corresponding score in `sbi_lens`
     - [ ] without score 
     - [ ] with score
